name: InspIRCd
version: 0.1.1
slug: inspircd
description: IRC server
url: https://github.com/TECH7Fox/inspircd-add-on
#image: "ghcr.io/tech7fox/{arch}-addon-inspircd"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - config:rw
  - ssl
options:
  password: password123
schema:
  password: password?
host_network: true
init: false
